### ISSUE TITLE
It's totally suck. Unable to uninstall

### ISSUE THREAD

**Issue by er-gaurav-sharma** [venustheme/brand#1]
Hello there,

How we can uninstall the extension as there is no class that defined the method to remove the schema and data. My website is just sucked by these foolish people. Is there a way to manually remove the module.

thanks

**Comment by venustheme** [comment]
Hello Gaurav,

Please try to run the command code in the terminal of your webroot.

*php -f magento module:uninstall Ves_Brand --backup-code --backup-media
--backup-db*

Or

*magento module:uninstall Ves_Brand --backup-code --backup-media
--backup-db*

Please find more information about uninstall module at here:
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html

On Wed, Jan 6, 2016 at 6:04 PM, er-gaurav-sharma <notifications@github.com>
wrote:

> Hello there,
>
> How we can uninstall the extension as there is no class that defined the
> method to remove the schema and data My website is just sucked by these
> foolish people Is there a way to manually remove the module
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venustheme/brand/issues/1>.
>



-- 
Best Regard

*VenusTheme Team*

Site: http://www.venustheme.com
Our Service:  http://www.venustheme.com/service
Skype: thuanlq88
Email: venustheme@gmail.com

**Comment by er-gaurav-sharma** [comment]
I have already used this but i got message sort of like "it is not in composer package"

thanks

**Comment by er-gaurav-sharma** [comment]
this is the exact error i got when uninstall "Ves_Brand is not an installed composer package
"
thanks

**Comment by er-gaurav-sharma** [comment]
you foolish people reply me asap. How can i completely remove this module. Have you ever been tested this is official magento 2.0. It just sucked does not event install over there

**Comment by venustheme** [comment]
Hello,

The extension we passed test for magento 2 fresh and magento 2 with sample
data. Also we are using it in our demo:

We just follow magento 2 command to uninstall the module. If not, please
try to manually remove it:

- Edit file "app/etc/config.php" then remove the line code:

'Ves_Brand' => 1,

- Delete folder "app/code/Ves/Brand/"

- Delete product attribute "Product Brand"

- Delete database tables:

ves_brand
ves_brand_store
ves_brand_group

On Fri, Jan 8, 2016 at 12:28 AM, er-gaurav-sharma <notifications@github.com>
wrote:

> you foolish people reply me asap. How can i completely remove this module.
> Have you ever been tested this is official magento 2.0. It just sucked does
> not event install over there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venustheme/brand/issues/1#issuecomment-169745486>.
>



-- 
Best Regard

*VenusTheme Team*

Site: http://www.venustheme.com
Our Service:  http://www.venustheme.com/service
Skype: thuanlq88
Email: venustheme@gmail.com

**Comment by interequipment** [comment]
This module broke my website. Now I cannot open create new product page after I delete ves_brand, ves_brand_store, ves_brand_group tables. Please help me to fix the issue.

**Comment by ashokbhadra** [comment]
DELETE FROM  `core_config_data`  WHERE path LIKE '%Ves%'
DELETE FROM `eav_attribute` WHERE source_model LIKE '%Ves%' 
DELETE FROM `setup_module` WHERE module LIKE '%Ves%' 

Should fix the problem.  I wasted quite a bit of time figuring this one out, hope it helps others.
