### ISSUE TITLE
Does not install on Official Magento 2.0

### ISSUE THREAD

**Issue by er-gaurav-sharma** [venustheme/brand#2]
you foolish people reply me asap. How can i completely remove this module. Have you ever been tested this is official magento 2.0. It just sucked does not event install over there

**Comment by venustheme** [comment]
Hello,

The extension we passed test for magento 2 fresh and magento 2 with sample
data. Also we are using it in our demo:

We just follow magento 2 command to uninstall the module. If not, please
try to manually remove it:

- Edit file "app/etc/config.php" then remove the line code:

'Ves_Brand' => 1,

- Delete folder "app/code/Ves/Brand/"

- Delete product attribute "Product Brand"

- Delete database tables:

ves_brand
ves_brand_store
ves_brand_group

On Fri, Jan 8, 2016 at 12:30 AM, er-gaurav-sharma <notifications@github.com>
wrote:

> you foolish people reply me asap How can i completely remove this module
> Have you ever been tested this is official magento 20 It just sucked does
> not event install over there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venustheme/brand/issues/2>.
>



-- 
Best Regard

*VenusTheme Team*

Site: http://www.venustheme.com
Our Service:  http://www.venustheme.com/service
Skype: thuanlq88
Email: venustheme@gmail.com

**Comment by er-gaurav-sharma** [comment]
There is php fatal error produced when we do magento:setup_upgrade. Furthermore when we visit the website Brand Group url, all brands url links are broken just display white screen of death. Please see the issue why it is broken the link.

thanks

**Comment by baomagento** [comment]
Hello Mate,

Please add new code layout=”2columns-left” as my screenshot in 3 files:
1. File /app/code/Ves/Brand/view/frontend/layout/vesbrand_index_index.xml
http://storage3.static.itmages.com/i/16/0223/h_1456234266_7160631_e168495dd1.png
 
2. File /app/code/Ves/Brand/view/frontend/layout/vesbrand_group_view.xml
http://storage4.static.itmages.com/i/16/0223/s_1456234185_6477731_a4ddf241ab.png
 
3. /app/code/Ves/Brand/view/frontend/layout/vesbrand_brand_view.xml
http://storage1.static.itmages.com/i/16/0223/h_1456234131_5300230_23f95147e2.png
