### ISSUE TITLE
Error: URL key already exists. 1

### ISSUE THREAD

**Issue by code-K** [venustheme/brand#5]
Hi there,

when doing the setup:upgrade command there come's currently an issue:

[Magento\Framework\Exception\LocalizedException]  
URL key already exists.1

Can you please let me know how to fix this?

Thanks much and best regards,
Christian

**Comment by venustheme** [comment]
Hello Mate,

Please send the information to confirm that you have purchased the theme
from us , then i will sent you latest module to update your issue.

On Tue, Mar 1, 2016 at 6:11 PM, Christian Koch <notifications@github.com>
wrote:

> Hi there,
>
> when doing the setup:upgrade command there come's currently an issue:
>
> [Magento\Framework\Exception\LocalizedException]
>
> URL key already exists.1
>
> Can you please let me know how to fix this?
>
> Thanks much and best regards,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/venustheme/brand/issues/5>.
>



-- 
Best Regard

*VenusTheme Team*

Site: http://www.venustheme.com
Our Service:  http://www.venustheme.com/service
Skype: thuanlq88
Email: venustheme@gmail.com

**Comment by varga** [comment]
I have the same error.

What's wrong and how can I fix it?

**Comment by varga** [comment]
I solved. Erased the records in db and worked.
